### ISSUE TITLE
AttributeError: 'EventList' object has no attribute 'populate_cpu_children'

### ISSUE THREAD

**Issue by shiyongde** [awwong1/torchprof#3]
>>> import torch
>>> import torchvision
>>> import torchprof
>>>
>>> model = torchvision.models.alexnet(pretrained=False).cuda()

>>> x = torch.rand([1, 3, 224, 224]).cuda()
>>>
>>> with torchprof.Profile(model, use_cuda=True) as prof:
...     model(x)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 43, in forward
    x = self.features(x)
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/ /annaconda3/envs/condamask/lib/python3.6/site-packages/torchprof/profile.py", line 72, in wrap_forward
    event_list.populate_cpu_children()
AttributeError: 'EventList' object has no attribute 'populate_cpu_children'

**Comment by awwong1** [comment]
What version of pytorch are you using?
EDIT: [Looks like that method was added for PyTorch v1.1.0](https://github.com/pytorch/pytorch/commit/7a8bc85f478b11fde20525a717b7cc3a72a5a6b2)

**Comment by shiyongde** [comment]
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

python  --version
Python 3.6.8 :: Anaconda, Inc.


Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.1.post2

**Comment by awwong1** [comment]
[Enforced minimum torch version of 1.1.0](https://github.com/awwong1/torchprof/commit/ac301cb28b55ff70ea1085364f991920498e85dc)
